//! This module defines the intermediate database schema representation that will be
//! used by the schema parser and the code generator. The AbstractDbRepr (ADR) struct
//! represents a database database in a canonical model. It will be referenced as ADR or
//! Internal Representation (IR). It can be seen as a contract between the templates and carpathia.
//!
use log::debug;
use std::{
    collections::{BTreeMap, BTreeSet},
    str::FromStr,
};

/// The version of the ADR - it has nothing to do with the software version of carpathia -
/// it only references to the ADR itself. Exprect for
///
/// - Mayor changes e.g. 0.1.0 to 1.0.0 changes that will break your templates which worked
///   fine under 0.1.0.
/// - Minor changes e.g. 0.1.0 to 0.2.0 will not break you themplates but allow you to enlarge them if needed.
///   A change like this will for example add new attributes to the ADR.
/// - Patch changes e.g. 0.1.0 to 0.1.1 will just fix bugs e.g. if the database constrant UNIQUE would have ben
///   given back as none, fixig it to return unique would be such a change.
pub const ABSTRACT_DB_REPR_VERSION: &str = "0.1.0";

/// Wrapping structure holding the database representation.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AbstractDbRepr {
    /// The version of ADR
    pub version: String,
    /// Tables found in the database - they are always in a deterministic order
    pub tables: BTreeMap<String, AbstractTableRepr>,
    /// Views found in the database - always in a deterministic order
    pub views: BTreeMap<String, AbstractTableRepr>,
}

/// This struct represents a table-like database object. This can be a
///
/// - table
/// - view
/// - materalized view
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AbstractTableRepr {
    pub object_type: ObjectType,
    /// Your data types mapping go into u_imports. Again the order is deterministic.
    pub u_imports: BTreeSet<String>,
    /// The name of the database object.
    pub table_name: String,
    /// language safe name of the database object. This is the name you will use in your templates to reference the database object.
    pub u_table_name: String,
    pub table_properties: BTreeSet<TableProperties>,
    pub comment: Option<String>,
    /// The attributes the database object consists of.
    pub attributes: BTreeMap<String, AbstractAttribute>,
}

/// This module defines the intermediate database attribute representation.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AbstractAttribute {
    pub column_name: String,
    /// language safe name of the database attribute. This is the name you will use in your templates to reference the database attribute.
    pub u_column_name: String,
    pub data_type: String,
    pub u_type: String,
    pub is_nullable: IsNullable,
    pub column_default: Option<String>,
    pub is_primary_key: bool,
    //pub character_maximum_length: Option<i32>,
    //pub numeric_precision: Option<i32>,
    //pub numeric_scale: Option<i32>,
    //pub is_identity: IsIdentity,
    //pub identity_generation: Option<String>,
    //pub is_generated: IsGenerated,
    //pub generation_expression: Option<String>,
    pub constraints: BTreeMap<ConstraintType, AbstractConstraint>,
    /*pub constraint_name: Option<String>,
    pub constraint_type: ConstraintType,
    pub referenced_table: Option<String>,
    pub referenced_column: Option<String>,
    */
    pub comment: Option<String>,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub struct AbstractConstraint {
    pub constraint_name: String,
    pub constraint_value: String,
    pub referenced_schema_name: Option<String>,
    pub referenced_table: Option<String>,
    pub u_referenced_table: Option<String>,
    pub referenced_column: Option<String>,
    pub u_referenced_column: Option<String>,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum TableProperties {
    PrimaryKey,
    Autogenerated,
    ForeignKey,
    Selectable,
    Insertable,
    Deletable,
    Updatable,
    NotNull,
    Nullable,
    Default,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum ObjectType {
    BaseTable,
    PartitionedTable,
    View,
    MaterializedView,
    Other,
    Unknown(String),
}

impl FromStr for ObjectType {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "base table" => Ok(ObjectType::BaseTable),
            "partitioned table" => Ok(ObjectType::PartitionedTable),
            "view" => Ok(ObjectType::View),
            "materialized view" => Ok(ObjectType::MaterializedView),
            _ => {
                debug!("Invalid object type: {}", s);
                Ok(ObjectType::Unknown(s.to_string()))
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsNullable {
    Yes,
    No,
    Unknown(String),
}

impl FromStr for IsNullable {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "yes" => Ok(IsNullable::Yes),
            "no" => Ok(IsNullable::No),
            _ => {
                debug!("Invalid value for is_nullable: {}", s);
                Ok(IsNullable::Unknown(s.to_string()))
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsIdentity {
    Yes,
    No,
    Unknown(String),
}

impl FromStr for IsIdentity {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "yes" => Ok(IsIdentity::Yes),
            "no" => Ok(IsIdentity::No),
            _ => {
                debug!("Invalid value for is_identity: {}", s);
                Ok(IsIdentity::Unknown(s.to_string()))
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsGenerated {
    Always,
    ByDefault,
    ByDefaultOnNull,
    Never,
    Unknown(String),
}

impl FromStr for IsGenerated {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "always" => Ok(IsGenerated::Always),
            "by default" => Ok(IsGenerated::ByDefault),
            "by default on null" => Ok(IsGenerated::ByDefaultOnNull),
            "never" => Ok(IsGenerated::Never),
            _ => {
                debug!("Invalid value for is_generated: {}", s);
                Ok(IsGenerated::Unknown(s.to_string()))
            }
        }
    }
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum ConstraintType {
    PrimaryKey,
    ForeignKey,
    Unique,
    Check,
    Exclusion,
    NotNull,
    ConstraintTrigger,
    None,
    Unknown(String),
}

impl FromStr for ConstraintType {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "p" | "primary key" => Ok(ConstraintType::PrimaryKey),
            "u" | "unique" => Ok(ConstraintType::Unique),
            "f" | "foreign key" => Ok(ConstraintType::ForeignKey),
            "c" | "check" => Ok(ConstraintType::Check),
            "x" | "exclusion" => Ok(ConstraintType::Exclusion),
            "n" | "not null" => Ok(ConstraintType::NotNull),
            "t" | "constraint trigger" => Ok(ConstraintType::ConstraintTrigger),
            "" | "none" => Ok(ConstraintType::None),
            _ => {
                debug!("Invalid constraint type: {}", s);
                Ok(ConstraintType::Unknown(s.to_string()))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_column_info(column_name: &str) -> AbstractAttribute {
        AbstractAttribute {
            column_name: column_name.to_string(),
            u_column_name: column_name.to_string(),
            data_type: "integer".to_string(),
            u_type: "whatever".to_string(),
            is_nullable: "NO".parse().unwrap_or(IsNullable::No),
            is_primary_key: false,
            column_default: Some("nextval('users_id_seq'::regclass)".to_string()),
            constraints: {
                let mut constraints = BTreeMap::new();
                constraints.insert(
                    ConstraintType::PrimaryKey,
                    AbstractConstraint {
                        constraint_name: "users_pkey".to_string(),
                        constraint_value: "".to_string(),
                        referenced_schema_name: None,
                        u_referenced_column: None,
                        referenced_table: None,
                        u_referenced_table: None,
                        referenced_column: None,
                    },
                );
                constraints
            },
            comment: Some("Primary key for users table".to_string()),
        }
    }
    fn create_table_info(table_name: &str) -> AbstractTableRepr {
        AbstractTableRepr {
            table_name: table_name.to_string(),
            u_table_name: table_name.to_string(),
            object_type: "BASE TABLE".parse().unwrap_or(ObjectType::BaseTable),
            attributes: BTreeMap::new(),
            u_imports: BTreeSet::new(),
            table_properties: BTreeSet::new(),
            comment: Some("Users table".to_string()),
        }
    }

    #[test]
    fn test_abstract_db_repr() {
        let mut table_info = create_table_info("users");
        assert_eq!(table_info.table_name, "users");
        table_info
            .attributes
            .insert("id".to_string(), create_column_info("id")); // Attempt to add a first attribute
        assert_eq!(table_info.attributes.len(), 1);
        table_info
            .attributes
            .insert("id".to_string(), create_column_info("id")); // Attempt to add a duplicate attribute
        assert_eq!(table_info.attributes.len(), 1);
        table_info
            .attributes
            .insert("name".to_string(), create_column_info("name")); // Add a new attribute
        assert_eq!(table_info.attributes.len(), 2);
        table_info
            .attributes
            .insert("name".to_string(), create_column_info("name")); // Attempt to add a duplicate attribute again
        assert_eq!(table_info.attributes.len(), 2);
    }

    #[test]
    fn test_constraint_type_from_str() {
        let primary_key: ConstraintType = "PRIMARY KEY".parse().unwrap();
        assert_eq!(primary_key, ConstraintType::PrimaryKey);

        let unique: ConstraintType = "UNIQUE".parse().unwrap();
        assert_eq!(unique, ConstraintType::Unique);

        let foreign_key: ConstraintType = "FOREIGN KEY".parse().unwrap();
        assert_eq!(foreign_key, ConstraintType::ForeignKey);

        let check: ConstraintType = "CHECK".parse().unwrap();
        assert_eq!(check, ConstraintType::Check);

        let exclusion: ConstraintType = "EXCLUSION".parse().unwrap();
        assert_eq!(exclusion, ConstraintType::Exclusion);

        let not_null: ConstraintType = "NOT NULL".parse().unwrap();
        assert_eq!(not_null, ConstraintType::NotNull);

        let constraint_trigger: ConstraintType = "CONSTRAINT TRIGGER".parse().unwrap();
        assert_eq!(constraint_trigger, ConstraintType::ConstraintTrigger);

        let none: ConstraintType = "NONE".parse().unwrap();
        assert_eq!(none, ConstraintType::None);

        let unknown: ConstraintType = "UNKNOWN".parse().unwrap();
        assert_eq!(unknown, ConstraintType::Unknown("UNKNOWN".to_string()));
    }

    #[test]
    fn test_is_nullable_from_str() {
        let yes: IsNullable = "YES".parse().unwrap();
        assert_eq!(yes, IsNullable::Yes);
        let unknown: IsNullable = "MAYBE".parse().unwrap();
        assert_eq!(unknown, IsNullable::Unknown("MAYBE".to_string()));
    }

    #[test]
    fn test_is_identity_from_str() {
        let yes: IsIdentity = "YES".parse().unwrap();
        assert_eq!(yes, IsIdentity::Yes);
        let unknown: IsIdentity = "MAYBE".parse().unwrap();
        assert_eq!(unknown, IsIdentity::Unknown("MAYBE".to_string()));
    }

    #[test]
    fn test_is_generated_from_str() {
        let always: IsGenerated = "ALWAYS".parse().unwrap();
        assert_eq!(always, IsGenerated::Always);
        let unknown: IsGenerated = "MAYBE".parse().unwrap();
        assert_eq!(unknown, IsGenerated::Unknown("MAYBE".to_string()));
        let by_default: IsGenerated = "BY DEFAULT".parse().unwrap();
        assert_eq!(by_default, IsGenerated::ByDefault);
        let by_default_on_null: IsGenerated = "BY DEFAULT ON NULL".parse().unwrap();
        assert_eq!(by_default_on_null, IsGenerated::ByDefaultOnNull);
        let never: IsGenerated = "NEVER".parse().unwrap();
        assert_eq!(never, IsGenerated::Never);
    }
}
