//! This module defines the intermediate database schema representation that will be
//! used by the schema parser and the code generator. The AbstractDbRepr (ADR) struct
//! represents a database database in a canonical model. It will be referenced as ADR or
//! Internal Representation (IR). It can be seen as a contract between the templates and carpathia.
//!
use std::collections::{BTreeMap, BTreeSet};

/// The version of the ADR - it has nothing to do with the software version of carpathia -
/// it only references to the ADR itself. Exprect for
///
/// - Mayor changes e.g. 0.1.0 to 1.0.0 changes that will break your templates which worked
///   fine under 0.1.0.
/// - Minor changes e.g. 0.1.0 to 0.2.0 will not break you themplates but allow you to enlarge them if needed.
///   A change like this will for example add new attributes to the ADR.
/// - Patch changes e.g. 0.1.0 to 0.1.1 will just fix bugs e.g. if the database constrant UNIQUE would have ben
///   given back as none, fixig it to return unique would be such a change.
pub const ABSTRACT_DB_REPR_VERSION: &str = "0.1.0";

/// Wrapping structure holding the database representation.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AbstractDbRepr {
    /// The version of ADR
    pub version: String,
    /// Tables found in the database - they are always in a deterministic order
    pub tables: BTreeMap<String, AbstractTableRepr>,
    /// Views found in the database - always in a deterministic order
    pub views: BTreeMap<String, AbstractTableRepr>,
}

/// This struct represents a table-like database object. This can be a
///
/// - table
/// - view
/// - materalized view
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AbstractTableRepr {
    pub object_type: ObjectType,
    /// Your data types mapping go into u_imports. Again the order is deterministic.
    pub u_imports: BTreeSet<String>,
    /// The name of the database object.
    pub table_name: String,
    /// language safe name of the database object. This is the name you will use in your templates to reference the database object.
    pub u_table_name: String,
    pub table_properties: BTreeSet<TableProperties>,
    pub comment: Option<String>,
    /// The attributes the database object consists of.
    pub attributes: BTreeMap<String, AbstractAttribute>,
}

/// This module defines the intermediate database attribute representation.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AbstractAttribute {
    pub column_name: String,
    /// language safe name of the database attribute. This is the name you will use in your templates to reference the database attribute.
    pub u_column_name: String,
    pub data_type: String,
    pub u_type: String,
    pub is_nullable: IsNullable,
    pub column_default: Option<String>,
    pub is_primary_key: bool,
    pub character_maximum_length: Option<i32>,
    pub numeric_precision: Option<i32>,
    pub numeric_scale: Option<i32>,
    //pub is_identity: IsIdentity,
    //pub identity_generation: Option<String>,
    //pub is_generated: IsGenerated,
    //pub generation_expression: Option<String>,
    pub constraints: BTreeMap<ConstraintType, AbstractConstraint>,
    /*pub constraint_name: Option<String>,
    pub constraint_type: ConstraintType,
    pub referenced_table: Option<String>,
    pub referenced_column: Option<String>,
    */
    pub comment: Option<String>,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub struct AbstractConstraint {
    pub constraint_name: String,
    pub constraint_value: String,
    pub referenced_schema_name: Option<String>,
    pub referenced_table: Option<String>,
    pub u_referenced_table: Option<String>,
    pub referenced_column: Option<String>,
    pub u_referenced_column: Option<String>,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum TableProperties {
    PrimaryKey,
    Autogenerated,
    ForeignKey,
    Selectable,
    Insertable,
    Deletable,
    Updatable,
    NotNull,
    Nullable,
    Default,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum ObjectType {
    BaseTable,
    PartitionedTable,
    View,
    MaterializedView,
    Other,
    Unknown(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsNullable {
    Yes,
    No,
    Unknown(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsIdentity {
    Yes,
    No,
    Unknown(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsGenerated {
    Always,
    ByDefault,
    ByDefaultOnNull,
    Never,
    Unknown(String),
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum ConstraintType {
    PrimaryKey,
    ForeignKey,
    Unique,
    Check,
    Exclusion,
    NotNull,
    ConstraintTrigger,
    None,
    Unknown,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_column_info(column_name: &str) -> AbstractAttribute {
        AbstractAttribute {
            column_name: column_name.to_string(),
            u_column_name: column_name.to_string(),
            data_type: "integer".to_string(),
            u_type: "whatever".to_string(),
            is_nullable: IsNullable::No,
            is_primary_key: false,
            column_default: Some("nextval('users_id_seq'::regclass)".to_string()),
            numeric_precision: None,
            numeric_scale: None,
            character_maximum_length: None,
            constraints: {
                let mut constraints = BTreeMap::new();
                constraints.insert(
                    ConstraintType::PrimaryKey,
                    AbstractConstraint {
                        constraint_name: "users_pkey".to_string(),
                        constraint_value: "".to_string(),
                        referenced_schema_name: None,
                        u_referenced_column: None,
                        referenced_table: None,
                        u_referenced_table: None,
                        referenced_column: None,
                    },
                );
                constraints
            },
            comment: Some("Primary key for users table".to_string()),
        }
    }
    fn create_table_info(table_name: &str) -> AbstractTableRepr {
        AbstractTableRepr {
            table_name: table_name.to_string(),
            u_table_name: table_name.to_string(),
            object_type: ObjectType::BaseTable,
            attributes: BTreeMap::new(),
            u_imports: BTreeSet::new(),
            table_properties: BTreeSet::new(),
            comment: Some("Users table".to_string()),
        }
    }

    #[test]
    fn test_abstract_db_repr() {
        let mut table_info = create_table_info("users");
        assert_eq!(table_info.table_name, "users");
        table_info
            .attributes
            .insert("id".to_string(), create_column_info("id")); // Attempt to add a first attribute
        assert_eq!(table_info.attributes.len(), 1);
        table_info
            .attributes
            .insert("id".to_string(), create_column_info("id")); // Attempt to add a duplicate attribute
        assert_eq!(table_info.attributes.len(), 1);
        table_info
            .attributes
            .insert("name".to_string(), create_column_info("name")); // Add a new attribute
        assert_eq!(table_info.attributes.len(), 2);
        table_info
            .attributes
            .insert("name".to_string(), create_column_info("name")); // Attempt to add a duplicate attribute again
        assert_eq!(table_info.attributes.len(), 2);
    }

    #[test]
    fn test_is_nullable_from_str() {
        let yes: IsNullable = IsNullable::Yes;
        assert_eq!(yes, IsNullable::Yes);
        let unknown: IsNullable = IsNullable::Unknown("MAYBE".to_string());
        assert_eq!(unknown, IsNullable::Unknown("MAYBE".to_string()));
    }

    #[test]
    fn test_is_identity_from_str() {
        let yes: IsIdentity = IsIdentity::Yes;
        assert_eq!(yes, IsIdentity::Yes);
        let unknown: IsIdentity = IsIdentity::Unknown("MAYBE".to_string());
        assert_eq!(unknown, IsIdentity::Unknown("MAYBE".to_string()));
    }
}
