//! This module defines the intermediate database schema representation that will be
//! used by the schema parser and the code generator. The AbstractDbRepr (ADR) struct
//! represents a database database in a canonical model. It will be referenced as ADR or
//! Internal Representation (IR). It can be seen as a contract between the templates and carpathia.
//!
use serde::{Deserialize, Serialize};
use std::cmp::Ordering;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::hash::Hash;
use std::ops::Add;
/// The version of the ADR - it has nothing to do with the software version of carpathia -
/// it only references to the ADR itself. Exprect for
///
/// - Mayor changes e.g. 0.1.0 to 1.0.0 changes that will break your templates which worked
///   fine under 0.1.0.
/// - Minor changes e.g. 0.1.0 to 0.2.0 will not break you themplates but allow you to enlarge them if needed.
///   A change like this will for example add new attributes to the ADR.
/// - Patch changes e.g. 0.1.0 to 0.1.1 will just fix bugs e.g. if the database constrant UNIQUE would have ben
///   given back as none, fixig it to return unique would be such a change.
pub const ABSTRACT_DB_REPR_VERSION: &str = env!("CARGO_PKG_VERSION");
const KEY_TYPE_CHANGE_DEFAULT: &KeyTypeChange = &KeyTypeChange {
    attribute_name: vec![],
    key_type: KeyType::SingleColumn,
};
/// Wrapping structure holding the database representation.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AbstractDbRepr {
    /// The version of ADR
    pub version: String,
    /// Tables found in the database - they are always in a deterministic order
    pub tables: BTreeMap<String, AbstractTableRepr>,
    /// Views found in the database - always in a deterministic order
    pub views: BTreeMap<String, AbstractTableRepr>,
}

/// This struct represents a table-like database object. This can be a
///
/// - table
/// - view
/// - materalized view
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AbstractTableRepr {
    pub object_type: ObjectType,
    /// Your data types mapping go into u_imports. Again the order is deterministic.
    pub u_imports: BTreeSet<String>,
    /// The name of the database object.
    pub table_name: String,
    /// language safe name of the database object. This is the name you will use in your templates to reference the database object.
    pub u_table_name: String,
    pub table_properties: BTreeSet<TableProperties>,
    pub comment: Option<String>,
    /// The attributes the database object consists of.
    pub attributes: BTreeMap<String, AbstractAttribute>,
}

/// This module defines the intermediate database attribute representation.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AbstractAttribute {
    pub column_name: String,
    /// language safe name of the database attribute. This is the name you will use in your templates to reference the database attribute.
    pub u_column_name: String,
    pub data_type: String,
    pub u_type: String,
    pub is_nullable: IsNullable,
    pub column_default: Option<String>,
    pub is_primary_key: bool,
    pub character_maximum_length: Option<i32>,
    pub numeric_precision: Option<i32>,
    pub numeric_scale: Option<i32>,
    //pub is_identity: IsIdentity,
    //pub identity_generation: Option<String>,
    //pub is_generated: IsGenerated,
    //pub generation_expression: Option<String>,
    pub constraints: BTreeMap<ConstraintType, AbstractConstraint>,
    /*pub constraint_name: Option<String>,
    pub constraint_type: ConstraintType,
    pub referenced_table: Option<String>,
    pub referenced_column: Option<String>,
    */
    pub comment: Option<String>,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub struct AbstractConstraint {
    pub constraint_name: String,
    pub constraint_value: String,
    pub referenced_schema_name: Option<String>,
    pub referenced_table: Option<String>,
    pub u_referenced_table: Option<String>,
    pub referenced_column: Option<String>,
    pub u_referenced_column: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, Ord, PartialOrd)]
pub enum TableProperties {
    PrimaryKey(AbstractPrimaryKey),
    Autogenerated,
    ForeignKey(AbstractForeignKey),
    Selectable,
    Insertable,
    Deletable,
    Updatable,
    NotNull,
    Nullable,
    Default,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum KeyType {
    SingleColumn,
    MultiColumn,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AbstractForeignKey {
    pub columns: BTreeSet<AbstractReferencedTable>,
}

// Must implent PartialEq, Eq, PartialOrd, Ord to be able to perform
// addition under the codition equal is any AbstractForeignKey as a
// type and not taking its content in account.
impl PartialEq for AbstractForeignKey {
    fn eq(&self, _other: &Self) -> bool {
        true
    }
}

impl Eq for AbstractForeignKey {}

impl PartialOrd for AbstractForeignKey {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for AbstractForeignKey {
    fn cmp(&self, _other: &Self) -> Ordering {
        Ordering::Equal
    }
}

struct KeyTypeChange {
    attribute_name: Vec<String>,
    key_type: KeyType,
}

impl Add for AbstractForeignKey {
    type Output = Self;

    fn add(self, other: Self) -> Self {
        //let other_columns = other.columns;
        let mut other_columns: BTreeSet<AbstractReferencedTable> = BTreeSet::new();
        let mut changed_key_types: HashMap<String, KeyTypeChange> = HashMap::new();
        for column in self.columns.iter().chain(other.columns.iter()) {
            if let Some(existing) = changed_key_types.get_mut(&column.constraint_name) {
                if !existing.attribute_name.contains(&column.column) {
                    existing.attribute_name.push(column.column.clone());
                    existing.key_type = KeyType::MultiColumn;
                } else if existing.attribute_name.contains(&column.column) {
                    // If the column is already present, we don't need to change the key type
                    // Done to prevent overwriting of the key type, which
                    // will result in losing the column names subsumed under this particlular
                    // constraint name. If removed this will result in a loss of information
                    // and will result in a wrong representation of the database schema.
                    let _ = -1; // No operation, just a placeholder to indicate no change
                }
            } else {
                changed_key_types.insert(
                    column.constraint_name.clone(),
                    KeyTypeChange {
                        attribute_name: vec![column.column.clone()],
                        key_type: KeyType::SingleColumn,
                    },
                );
            }
        }
        for column in self.columns.into_iter().chain(other.columns) {
            let key_type = changed_key_types
                .get(&column.constraint_name)
                .unwrap_or(KEY_TYPE_CHANGE_DEFAULT);
            other_columns.insert(AbstractReferencedTable {
                constraint_name: column.constraint_name,
                key_type: key_type.key_type.clone(),
                column: column.column,
                referenced_table: column.referenced_table,
                referenced_column: column.referenced_column,
            });
        }

        AbstractForeignKey {
            columns: other_columns,
        }
    }
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub struct AbstractReferencedTable {
    pub constraint_name: String,
    pub key_type: KeyType,
    pub column: String,
    pub referenced_table: String,
    pub referenced_column: String,
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub struct AbstractPrimaryKey {
    pub constraint_name: String,
    pub columns: BTreeSet<String>,
    pub key_type: KeyType,
}

impl Add for AbstractPrimaryKey {
    type Output = Self;

    fn add(self, other: Self) -> Self {
        let mut combined_columns = self.columns;
        combined_columns.extend(other.columns);
        let key_type = if combined_columns.len() > 1 {
            KeyType::MultiColumn
        } else {
            KeyType::SingleColumn
        };
        AbstractPrimaryKey {
            constraint_name: self.constraint_name,
            columns: combined_columns,
            key_type,
        }
    }
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum ObjectType {
    BaseTable,
    PartitionedTable,
    View,
    MaterializedView,
    Other,
    Unknown(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsNullable {
    Yes,
    No,
    Unknown(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsIdentity {
    Yes,
    No,
    Unknown(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum IsGenerated {
    Always,
    ByDefault,
    ByDefaultOnNull,
    Never,
    Unknown(String),
}

#[derive(
    Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, Ord, PartialOrd,
)]
pub enum ConstraintType {
    PrimaryKey,
    ForeignKey,
    Unique,
    Check,
    Exclusion,
    NotNull,
    ConstraintTrigger,
    None,
    Unknown,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_column_info(column_name: &str) -> AbstractAttribute {
        AbstractAttribute {
            column_name: column_name.to_string(),
            u_column_name: column_name.to_string(),
            data_type: "integer".to_string(),
            u_type: "whatever".to_string(),
            is_nullable: IsNullable::No,
            is_primary_key: false,
            column_default: Some("nextval('users_id_seq'::regclass)".to_string()),
            numeric_precision: None,
            numeric_scale: None,
            character_maximum_length: None,
            constraints: {
                let mut constraints = BTreeMap::new();
                constraints.insert(
                    ConstraintType::PrimaryKey,
                    AbstractConstraint {
                        constraint_name: "users_pkey".to_string(),
                        constraint_value: "".to_string(),
                        referenced_schema_name: None,
                        u_referenced_column: None,
                        referenced_table: None,
                        u_referenced_table: None,
                        referenced_column: None,
                    },
                );
                constraints
            },
            comment: Some("Primary key for users table".to_string()),
        }
    }
    fn create_table_info(table_name: &str) -> AbstractTableRepr {
        AbstractTableRepr {
            table_name: table_name.to_string(),
            u_table_name: table_name.to_string(),
            object_type: ObjectType::BaseTable,
            attributes: BTreeMap::new(),
            u_imports: BTreeSet::new(),
            table_properties: BTreeSet::new(),
            comment: Some("Users table".to_string()),
        }
    }
    #[test]
    fn test_abstract_foreign_key_addition() {
        let column1 = AbstractForeignKey {
            columns: BTreeSet::from([AbstractReferencedTable {
                constraint_name: "fk1".to_string(),
                key_type: KeyType::SingleColumn,
                column: "column1".to_string(),
                referenced_table: "ref_table1".to_string(),
                referenced_column: "ref_column1".to_string(),
            }]),
        };
        assert_eq!(column1.columns.len(), 1);
        assert_eq!(
            column1.columns.iter().next().unwrap().constraint_name,
            "fk1"
        );
        assert_eq!(
            column1.columns.iter().next().unwrap().key_type,
            KeyType::SingleColumn
        );
        // Adding the same foreign key again - it should still be a single column foreign key
        let column1_duplicate = column1.clone();
        let combined_fk = column1.clone() + column1_duplicate;
        assert_eq!(
            combined_fk.columns.len(),
            1,
            "Expected 1 column in combined foreign key, got {:?}",
            combined_fk
        );
        assert_eq!(
            combined_fk.columns.iter().next().unwrap().key_type,
            KeyType::SingleColumn,
            "Expected key_type to be SingleColumn {:?}",
            combined_fk
        );

        let column2 = AbstractForeignKey {
            columns: BTreeSet::from([AbstractReferencedTable {
                constraint_name: "fk1".to_string(),
                key_type: KeyType::SingleColumn,
                column: "column2".to_string(),
                referenced_table: "ref_table2".to_string(),
                referenced_column: "ref_column2".to_string(),
            }]),
        };

        let combined_fk = column1 + column2;

        assert_eq!(
            combined_fk.columns.len(),
            2,
            "Expected 2 columns in combined foreign key, got {:?}",
            combined_fk
        );
        assert_eq!(
            combined_fk
                .columns
                .iter()
                .find(|c| c.column == "column1")
                .unwrap()
                .key_type,
            KeyType::MultiColumn,
            "Expected column1 to have key_type MultiColumn {:?}",
            combined_fk
        );
        assert_eq!(
            combined_fk
                .columns
                .iter()
                .find(|c| c.column == "column2")
                .unwrap()
                .key_type,
            KeyType::MultiColumn,
            "Expected column2 to have key_type MultiColumn {:?}",
            combined_fk
        );

        let column3 = AbstractForeignKey {
            columns: BTreeSet::from([AbstractReferencedTable {
                constraint_name: "fk2".to_string(),
                key_type: KeyType::SingleColumn,
                column: "column3".to_string(),
                referenced_table: "ref_table3".to_string(),
                referenced_column: "ref_column3".to_string(),
            }]),
        };

        let combined_fk2 = combined_fk + column3;
        assert_eq!(
            combined_fk2.columns.len(),
            3,
            "Expected 3 columns in combined foreign key, got {:?}",
            combined_fk2
        );
        assert_eq!(
            combined_fk2
                .columns
                .iter()
                .find(|c| c.column == "column3")
                .unwrap()
                .key_type,
            KeyType::SingleColumn,
            "Expected column3 to have key_type SingleColumn {:?}",
            combined_fk2
        );
        assert_eq!(
            combined_fk2
                .columns
                .iter()
                .find(|c| c.column == "column1")
                .unwrap()
                .key_type,
            KeyType::MultiColumn,
            "Expected column1 to have key_type MultiColumn {:?}",
            combined_fk2
        );
        assert_eq!(
            combined_fk2
                .columns
                .iter()
                .find(|c| c.column == "column2")
                .unwrap()
                .key_type,
            KeyType::MultiColumn,
            "Expected column2 to have key_type MultiColumn {:?}",
            combined_fk2
        );
    }

    #[test]
    fn test_primary_key_addition() {
        let pk1 = AbstractPrimaryKey {
            constraint_name: "pk1".to_string(),
            columns: BTreeSet::from(["column1".to_string()]),
            key_type: KeyType::SingleColumn,
        };
        assert_eq!(pk1.constraint_name, "pk1");
        assert_eq!(pk1.columns, BTreeSet::from(["column1".to_string()]));
        assert_eq!(pk1.key_type, KeyType::SingleColumn);

        let pk2 = AbstractPrimaryKey {
            constraint_name: "pk2".to_string(),
            columns: BTreeSet::from(["column2".to_string()]),
            key_type: KeyType::SingleColumn,
        };

        let combined_pk = pk1 + pk2;

        assert_eq!(combined_pk.constraint_name, "pk1");
        assert_eq!(
            combined_pk.columns,
            BTreeSet::from(["column1".to_string(), "column2".to_string()])
        );
        assert_eq!(combined_pk.key_type, KeyType::MultiColumn);
    }

    #[test]
    fn test_abstract_db_repr() {
        let mut table_info = create_table_info("users");
        assert_eq!(table_info.table_name, "users");
        table_info
            .attributes
            .insert("id".to_string(), create_column_info("id")); // Attempt to add a first attribute
        assert_eq!(table_info.attributes.len(), 1);
        table_info
            .attributes
            .insert("id".to_string(), create_column_info("id")); // Attempt to add a duplicate attribute
        assert_eq!(table_info.attributes.len(), 1);
        table_info
            .attributes
            .insert("name".to_string(), create_column_info("name")); // Add a new attribute
        assert_eq!(table_info.attributes.len(), 2);
        table_info
            .attributes
            .insert("name".to_string(), create_column_info("name")); // Attempt to add a duplicate attribute again
        assert_eq!(table_info.attributes.len(), 2);
    }

    #[test]
    fn test_is_nullable_from_str() {
        let yes: IsNullable = IsNullable::Yes;
        assert_eq!(yes, IsNullable::Yes);
        let unknown: IsNullable = IsNullable::Unknown("MAYBE".to_string());
        assert_eq!(unknown, IsNullable::Unknown("MAYBE".to_string()));
    }

    #[test]
    fn test_is_identity_from_str() {
        let yes: IsIdentity = IsIdentity::Yes;
        assert_eq!(yes, IsIdentity::Yes);
        let unknown: IsIdentity = IsIdentity::Unknown("MAYBE".to_string());
        assert_eq!(unknown, IsIdentity::Unknown("MAYBE".to_string()));
    }
}
