name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Testing with PostgreSQL ${{ matrix.pg }} and Pagila schema
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pg: [13, 14, 15, 16, 17, 18]

    services:
      postgres:
        image: postgres:${{ matrix.pg }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: carpathia
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Rust toolchain einrichten
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo Cache aktivieren
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Installing dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev postgresql-client

      - name: Providing Pagila-Schema
        run: cp fixtures/pagila-schema.sql pagila-schema.sql

      - name: Loading Pagila-Schema in PostgreSQL
        run: |
          until pg_isready -h localhost -U postgres; do
            sleep 1
          done
          psql -h localhost -U postgres -d carpathia -f pagila-schema.sql
          rm .env.test
        env:
          PGPASSWORD: postgres

      - name: Rust Linting (clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Running Tests
        run: cargo test
        env:
          TEST_DB_URL: postgres://postgres:postgres@localhost:5432
          TEST_DB_NAME: carpathia
